### ISSUE TITLE
string..h missing

### ISSUE THREAD

**Issue by Ntweat** [flanggut/smvs#19]
Hi I am getting the following error

smvsrecon.cc:23:25: fatal error: util/string.h: No such file or directory

I am trying to build on Ubuntu 16.04

**Comment by flanggut** [comment]
Hi, yes this was renamed in MVE and I wasn't able to push a fix yet. It should be fixed now thanks to #18.
